import './App.css';
import Hero from './components/custom/Hero';
import StudentExplorer from './components/custom/StudentExplorer';
import TravelVibe from './components/custom/TravelVibe';
import TravelMap from './components/custom/TravelMap';
import { Compass, Sparkles, Map as MapIcon, Shield, CreditCard, ListChecks, ArrowRight } from "lucide-react";

function App() {
  const features = [
    {
      title: "AI Itineraries",
      desc: "Get personalized travel plans generated by advanced AI models.",
      icon: <Sparkles className="w-8 h-8 text-blue-600" />,
      link: "/create-trip"
    },
    {
      title: "Budget Splitter",
      desc: "Perfect for group trips. Divide expenses seamlessly and fairly.",
      icon: <CreditCard className="w-8 h-8 text-indigo-600" />,
      link: "/budget-splitter"
    },
    {
      title: "Interactive Scratch Map",
      desc: "Visualize your journey with beautiful, data-rich interactive maps.",
      icon: <MapIcon className="w-8 h-8 text-blue-500" />,
      link: "#scratch-map"
    },
    {
      title: "Smart Packing",
      desc: "An AI-powered checklist to ensure you never forget your essentials.",
      icon: <ListChecks className="w-8 h-8 text-indigo-500" />,
      link: "/packing-checklist"
    }
  ];

  return (
    <div className="bg-white">
      <Hero />

      {/* Features Section */}
      <section className="py-24 px-6 md:px-16 bg-slate-50/50">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16 space-y-4">
            <h2 className="text-3xl md:text-5xl font-black text-slate-900 tracking-tight leading-tight">
              Reimagining How You <span className="text-blue-600">Travel</span>
            </h2>
            <p className="text-slate-600 text-lg max-w-2xl mx-auto">
              We've built a suite of tools designed to make your next adventure seamless, smart, and unforgettable.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {features.map((feature, index) => (
              <div
                key={index}
                onClick={() => {
                  if (feature.link) window.location.href = feature.link;
                }}
                className={`group p-8 bg-white rounded-3xl border border-slate-100 shadow-sm hover:shadow-xl hover:-translate-y-1 transition-all duration-300 ${feature.link ? 'cursor-pointer' : ''}`}
              >
                <div className="mb-6 p-3 bg-slate-50 rounded-2xl w-fit group-hover:scale-110 transition-transform duration-300">
                  {feature.icon}
                </div>
                <h3 className="text-xl font-bold text-slate-900 mb-3">{feature.title}</h3>
                <p className="text-slate-600 leading-relaxed text-sm">
                  {feature.desc}
                </p>
                {feature.link && (
                  <div className="mt-6 text-blue-600 font-bold text-sm flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                    Try It Now <ArrowRight className="w-4 h-4" />
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      <TravelVibe />
      <TravelMap />

      <StudentExplorer />

      {/* Trust Quote / Stats */}
      <section className="py-20 border-t border-slate-100 italic text-center">
        <p className="text-2xl text-slate-400 font-medium">"The future of travel planning is here, and it's powered by LetsGo."</p>
      </section>
    </div>
  )
}
export default App